baseURL = 'https://pics.pernazza.com/'
languageCode = 'en-us'
title = 'picport'

[params]
  description = "marco's photography portfolio"
  darkMode = true
  version = "v1.2"

[menu]
  [[menu.main]]
    identifier = "archive"
    name = "archive"
    url = "/archive/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "map"
    name = "map"
    url = "/map/"
    weight = 30

  [[menu.social]]
    identifier = "instagram"
    name = "instagram"
    url = "https://instagram.com/isoperny"
    weight = 10
  [[menu.social]]
    identifier = "email"
    name = "email"
    url = "mailto:marco@pernazza.com"
    weight = 20
